### ISSUE TITLE
train.py try to write files in to non existing directories

### ISSUE THREAD

**Issue by cahya-wirawan** [rajveermalviya/language-modeling#1]
**Describe the bug**
1. The training (python train.py) tries to write dictionary.json on not existing directory.
2. The training (python train.py) tries to save model-xx.h5  on not existing directory.
 
**To Reproduce**
$ git clone https://github.com/rajveermalviya/language-modeling.git
$ cd language-modeling
$ pip3 install -r requirements.txt
$ python train.py 

**Expected behavior**
The software should be able to write to dictionary.json and model-xx.h5 without any issue.

**Screenshots**

1. 

$python train.py 
...
None
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    os.getcwd(), 'web', 'web_model', 'dictionary.json'))
  File "/home/cahya/language-modeling/utils.py", line 50, in save_json
    with open(filename, 'w') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cahya/language-modeling/web/web_model/dictionary.json'

2. 

$python train.py 
...
3098/3098 [============================>.] - ETA: 0s - loss: 15.9780 - categorical_accuracy: 0.0085        
Epoch 00001: saving model to /home/cahya/language-modeling/model/checkpoint/model-01.h5
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    callbacks=[checkpointer],
...
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/home/cahya/language-modeling/model/checkpoint/model-01.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)

**Additional context**

**Comment by rajveermalviya** [comment]
@cahya-wirawan 
Added notice to create required directories in [README.md](https://github.com/rajveermalviya/language-modeling/blob/master/README.md) file.
